---
abstract: 'DBI Authentication back end for PlugAuth'
author:
  - 'Graham Ollis <gollis@sesda3.com>'
build_requires:
  File::HomeDir: 0
  File::HomeDir::Test: 0
  File::Spec: 0
  PlugAuth: 0
  Test::Differences: 0
  Test::More: 0
  Test::PlugAuth::Plugin::Auth: 0
  YAML: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300021, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PlugAuth-Plugin-DBIAuth
requires:
  Crypt::PasswdMD5: 0
  DBI: 0
  Log::Log4perl: 0
  PlugAuth: 0
  PlugAuth::Role::Auth: 0
  PlugAuth::Role::Plugin: 0
  Role::Tiny::With: 0
resources:
  bugtracker: https://github.com/plicease/plugauth-plugin-dbiauth/issues
  homepage: http://perl.wdlabs.com/PlugAuth-Plugin-DBIAuth/
  repository: git://github.com/plicease/plugauth-plugin-dbiauth.git
version: 0.03
